#cloud-config
hostname: ubuntu-server
manage_etc_hosts: true

users:
  - name: admin
    groups: [adm, sudo]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC...

packages:
  - curl
  - vim
  - htop
  - git

package_update: true
package_upgrade: true

runcmd:
  - systemctl enable ssh
  - ufw enable

final_message: "Ubuntu Server configuration complete!"
